### ISSUE TITLE
AWS node creation fails on Chef master

### ISSUE THREAD

**Issue by tylercloke** [chef/qa-chef-server-cluster#51] opened 2015-06-09 18:10 UTC
Using chef / knife from this commit https://github.com/chef/chef/commit/eb590e371b5e5d3f4d1d201dd3f58e4351116f41

```
chef-client -z -o qa-chef-server-cluster
<...>
  - update node standalone at chefzero://localhost:8889
    -   update run_list from ["recipe[qa-chef-server-cluster::standalone]"] to ["qa-chef-server-cluster::standalone"][2015-06-09T11:04:42-07:00] INFO: Executing sudo cp /etc/chef/client.pem /tmp/client.pem.2103421544 on ubuntu@10.194.27.11
[2015-06-09T11:04:52-07:00] ERROR: Unable to download /etc/chef/client.pem to /tmp/client.pem.2103421544 on ubuntu@10.194.27.11 -- execution expired
[2015-06-09T11:04:52-07:00] INFO: Executing sudo rm /tmp/client.pem.2103421544 on ubuntu@10.194.27.11
[2015-06-09T11:05:02-07:00] WARN: Unable to clean up /tmp/client.pem.2103421544 on ubuntu@10.194.27.11 -- execution expired
[2015-06-09T11:05:02-07:00] INFO: Processing private_key[in_memory] action create (basic_chef_client::block line 79)
[2015-06-09T11:05:02-07:00] WARN: Class Chef::Provider::PrivateKey does not declare 'provides :private_key'.
[2015-06-09T11:05:02-07:00] WARN: This will no longer work in Chef 13: you must use 'provides' to provide DSL.
[2015-06-09T11:05:02-07:00] INFO: Running queued delayed notifications before re-raising exception

    ================================================================================
    Error executing action `converge` on resource 'machine[standalone]'
    ================================================================================

    RuntimeError
    ------------
    private_key[in_memory] (basic_chef_client::block line 79) had an error: RuntimeError: Could not read private key from none: missing pass phrase?

    Resource Declaration:
    ---------------------
    # In /Users/tyler/oc/qa-chef-server-cluster/.chef/local-mode-cache/cache/cookbooks/qa-chef-server-cluster/recipes/standalone-server.rb

     23: machine 'standalone' do
     24:   run_list ['qa-chef-server-cluster::standalone']
     25:   attribute 'qa-chef-server-cluster', node['qa-chef-server-cluster']
     26: end
     27:

    Compiled Resource:
    ------------------
    # Declared in /Users/tyler/oc/qa-chef-server-cluster/.chef/local-mode-cache/cache/cookbooks/qa-chef-server-cluster/recipes/standalone-server.rb:23:in `from_file'

    machine("standalone") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"chefzero://localhost:8889", :options=>{:client_name=>"lyra.local", :signing_key_filename=>nil}}
      driver "aws::us-west-2"
      machine_options {:aws_tags=>{:"X-Project"=>"qa-chef-server-cluster"}, :use_private_ip_for_ssh=>true, :ssh_username=>"ubuntu", :bootstrap_options=>{:key_name=>"qa-chef-server-cluster-default", :subnet_id=>"subnet-6fab6818", :security_group_ids=>["sg-52a8f837"], :image_id=>"ami-3d50120d", :instance_type=>"m3.medium"}}
      declared_type :machine
      cookbook_name "qa-chef-server-cluster"
      recipe_name "standalone-server"
      run_list ["qa-chef-server-cluster::standalone"]
      attribute_modifiers [["qa-chef-server-cluster", {"chef-provisioner-key-name"=>"insecure-chef-provisioner", "aws"=>{"region"=>"us-west-2", "availability_zone"=>"b", "machine_options"=>{"aws_tags"=>{"X-Project"=>"qa-chef-server-cluster"}, "use_private_ip_for_ssh"=>true, "ssh_username"=>"ubuntu", "bootstrap_options"=>{"key_name"=>"qa-chef-server-cluster-default", "subnet_id"=>"subnet-6fab6818", "security_group_ids"=>["sg-52a8f837"], "image_id"=>"ami-3d50120d", "instance_type"=>"m3.medium"}}}, "chef-server-core"=>{"install"=>{"version"=>:latest_stable, "integration_builds"=>nil, "repo"=>nil}, "upgrade"=>{"version"=>:latest_current, "integration_builds"=>nil, "repo"=>nil}}, "opscode-manage"=>{"install"=>{"version"=>:latest_stable, "integration_builds"=>nil, "repo"=>nil}, "upgrade"=>{"version"=>"1.15.0", "integration_builds"=>nil, "repo"=>nil}}, "chef-ha"=>{"install"=>{"version"=>"1.0.0", "integration_builds"=>false, "repo"=>"omnibus-stable-local"}, "upgrade"=>{"version"=>"1.0.0", "integration_builds"=>nil, "repo"=>nil}}, "chef-server"=>{"api_fqdn"=>"api.chef.sh", "file-dir"=>"/Users/tyler/oc/qa-chef-server-cluster/.chef/../.chef/stash", "files"=>{"/etc/opscode/webui_priv.pem"=>"/Users/tyler/oc/qa-chef-server-cluster/.chef/../.chef/stash/webui_priv.pem", "/etc/opscode/webui_pub.pem"=>"/Users/tyler/oc/qa-chef-server-cluster/.chef/../.chef/stash/webui_pub.pem", "/etc/opscode/pivotal.pem"=>"/Users/tyler/oc/qa-chef-server-cluster/.chef/../.chef/stash/pivotal.pem", "/etc/opscode/private-chef-secrets.json"=>"/Users/tyler/oc/qa-chef-server-cluster/.chef/../.chef/stash/private-chef-secrets.json"}}}]]
    end

[2015-06-09T11:05:02-07:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-06-09T11:05:02-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-09T11:05:02-07:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 313.335583 seconds
[2015-06-09T11:05:03-07:00] FATAL: Stacktrace dumped to /Users/tyler/oc/qa-chef-server-cluster/.chef/local-mode-cache/cache/chef-stacktrace.out
[2015-06-09T11:05:03-07:00] ERROR: Found 1 errors, they are stored in the backtrace
[2015-06-09T11:05:03-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by tyler-ball** [comment] 2015-06-24 23:34
@tylercloke can you gist the full stacktrace from `.chef/local-mode-cache/cache/chef-stacktrace.out`?

**Comment by afiune** [comment] 2015-06-25 12:58
Trying to replicate this since many people is hitting this issue.. My only assumption is that it is coming from the newest release of `chefdk 0.6.2` 

@tylercloke what version of `chefdk` are you running on?

**Comment by afiune** [comment] 2015-06-25 14:02
Oh boy.. I can't get it to replicate in my machine! :sob: 

I installed latest chefdk `0.6.2` and the only issue I hit was:
```
ChefZero::ServerNotFound: No socketless chef-zero server on given port 8890
```

Which I fixed by updating my `gems` within `bundler` (don't ask)... Now it is working fine on latest.. We might need more info to replicate this. 

cc/ @jezhumble since he is hitting the same issue

**Comment by tyler-ball** [comment] 2015-06-25 16:45
Grr... @afiune the `ChefZero` issue is fixed in ChefDK 0.7.0 (currently only in RC) - you can download it from http://www.chef.io/chef/metadata-chefdk?p=mac_os_x&pv=10.10&m=x86_64&v=latest&prerelease=true&nightlies=false for OSX.  You can also modify that URL using the [omnitruck api](https://docs.chef.io/api_omnitruck.html).

Or if you're not afraid of curl-bash - `curl -LO https://www.chef.io/chef/install.sh && sudo bash ./install.sh -p -P chefdk && rm install.sh`

**Comment by afiune** [comment] 2015-06-25 16:47
I'll test it .. :)

On Thursday, June 25, 2015, Tyler Ball <notifications@github.com> wrote:

> Grr... @afiune <https://github.com/afiune> the ChefZero issue is fixed in
> ChefDK 0.7.0 (currently only in RC) - you can download it from
> http://www.chef.io/chef/metadata-chefdk?p=mac_os_x&pv=10.10&m=x86_64&v=latest&prerelease=true&nightlies=false
> for OSX. You can also modify that URL using the omnitruck api
> <https://docs.chef.io/api_omnitruck.html>.
>
> Or if you're not afraid of curl-bash - curl -LO
> https://www.chef.io/chef/install.sh && sudo bash ./install.sh -p -P
> chefdk && rm install.sh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/qa-chef-server-cluster/issues/51#issuecomment-115320916>
> .
>


-- 

*Salim Afiune* — Solutions Engineer

917.716.0448 – afiune@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/afiune>  Twitter <http://www.twitter.com/afiune>

CHEF

      CHEF.IO <http://www.chef.io/>

TM

*chef.io <http://www.chef.io/>*   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by afiune** [comment] 2015-06-25 20:45
I've got the stacktrace! Starting to dig into this.. :smile: 

```
RuntimeError: machine[chef-server-test] (delivery-cluster::setup_chef_server line 31) had an error: RuntimeError: private_key[in_memory] (basic_chef_client::block line 79) had an error: RuntimeError: Could not read private key from none: missing pass phrase?
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/chef/provider/private_key.rb:73:in `create_key'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/chef/provider/private_key.rb:8:in `block in <class:PrivateKey>'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/provider/lwrp_base.rb:160:in `instance_eval'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/provider/lwrp_base.rb:160:in `block in action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/provider.rb:140:in `run_action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource.rb:586:in `run_action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:49:in `run_action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:81:in `each'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:81:in `block in converge'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:69:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:133:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:133:in `with_chef_config'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:68:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:109:in `converge_block'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bundler/gems/chef-provisioning-ac770060c77e/lib/chef/provisioning.rb:12:in `inline_resource'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bundler/gems/chef-provisioning-ac770060c77e/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb:78:in `create_keys'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bundler/gems/chef-provisioning-ac770060c77e/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb:16:in `setup_convergence'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bundler/gems/chef-provisioning-ac770060c77e/lib/chef/provisioning/convergence_strategy/install_sh.rb:40:in `setup_convergence'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bundler/gems/chef-provisioning-ac770060c77e/lib/chef/provisioning/machine/basic_machine.rb:17:in `setup_convergence'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bundler/gems/chef-provisioning-ac770060c77e/lib/chef/provider/machine.rb:57:in `block in <class:Machine>'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/provider/lwrp_base.rb:46:in `block in action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/provider.rb:140:in `run_action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource.rb:586:in `run_action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:49:in `run_action'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:81:in `each'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:81:in `block in converge'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/runner.rb:80:in `converge'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/client.rb:654:in `block in converge'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/client.rb:649:in `catch'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/client.rb:649:in `converge'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/client.rb:688:in `converge_and_save'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/client.rb:269:in `run'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application.rb:270:in `block in fork_chef_client'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application.rb:258:in `fork'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application.rb:258:in `fork_chef_client'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application.rb:224:in `block in run_chef_client'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application.rb:212:in `run_chef_client'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application/client.rb:392:in `loop'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application/client.rb:382:in `run_application'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/lib/chef/application.rb:60:in `run'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/gems/chef-12.4.0/bin/chef-client:26:in `<top (required)>'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bin/chef-client:23:in `load'
/Users/jezhumble/.chefdk/gem/ruby/2.1.0/bin/chef-client:23:in `<main>'Jezs-iMac:delivery-cluster jezhumble$
```

**Comment by tyler-ball** [comment] 2015-06-30 19:37
@afiune Ah!  So, this issue is a duplicate of https://github.com/chef/chef-provisioning/issues/377 - the TL;DR is that chef client 12.4.0 doesn't work with chef provisioning so you need to use chef-client 12.3.0.  We're working on 12.4.1 which should resolve this issue.

**Comment by tyler-ball** [comment] 2015-06-30 19:38
(also, re-open this if you use a different github flow than us - because this is a duplicate our team would close it and keep working in the original bug)

**Closed by tyler-ball** 2015-06-30 19:37 UTC
Labels: bug
